name: Pipeline-github

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      #run: mvn clean install --settings .m2/settings.xml
      run: mvn -B package --file pom.xml
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: cobrojava-artifact
        path: target/

  sonatype-cli:
    runs-on: ubuntu-latest
    environment: Nexus
    needs: build
    steps:
      #Check out your code
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: cobrojava-artifact
          path: target
      # Perform an evaluation 
      - name: Run evaluate action 
        id: evaluate
        uses: sonatype/actions/evaluate@v1
        with:
          iq-server-url: http://52.234.210.127:8070/
          username: ${{ secrets.NEXUS_IQ_USERNAME }}
          password: ${{ secrets.NEXUS_IQ_PASSWORD }}
          application-id: CobroJava
          scan-targets: target/*.jar
          # upload-sarif-file: true
        
   